paths:
    migrations: %%PHINX_CONFIG_DIR%%/../migrations

environments:
    default_migration_table: phinxlog
    default_database: production
    production:
        adapter: sqlite
        name: %%PHINX_CONFIG_DIR%%/../storage/locomotive.sqlite
