lftp-path:
private-keyfile:
public-keyfile:
username:
password:
working-dir:
speed-limit: 0
connection-limit: 25
transfer-limit: 3
max-retries: 5
newer-than:
zip-sources: false
remove-sources:
  remove: false
  exclude:
speed-schedule:
source-target-map:
post-processors:
notifications:
  prowl:
    enable: false
    events: [transferStarted, itemMoved]
    api-key:
  pushover:
    enable: false
    events: [transferStarted, itemMoved]